[project]
name = "ml-telecom-customer-churn-deployment"
version = "0.1.0"
description = "Churn Prediction Service"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.121.1",
    "scikit-learn>=1.7.2",
    "uvicorn>=0.38.0",
]
